name: Publish nightly to NPM

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  publish:
    name: Publish to NPM (nightly)
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Check if token is set
        id: check-npm-token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "env NPM_TOKEN not set!"
          else
            echo ::set-output name=is-ok::"1"
          fi
      - name: Prepare Environment
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: |
          yarn
        env:
          CI: true
      - name: Get the Prerelease tag
        id: prerelease-tag
        uses: yuya-takeyama/docker-tag-from-github-ref-action@2b0614b1338c8f19dd9d3ea433ca9bc0cc7057ba
        with:
          remove-version-tag-prefix: false
      - name: Bump version to nightly
        if: ${{ steps.do-publish.outputs.publish }}
        run: |
          COMMIT_TIMESTAMP=$(git log -1 --pretty=format:%ct HEAD)
          COMMIT_DATE=$(date -d @$COMMIT_TIMESTAMP +%Y%m%d-%H%M%S)
          GIT_HASH=$(git rev-parse --short HEAD)
          PRERELEASE_TAG=nightly-$(echo "${{ steps.prerelease-tag.outputs.tag }}" | sed -r 's/[^a-z0-9]+/-/gi')
          yarn lerna:version $PRERELEASE_TAG-$COMMIT_DATE-$GIT_HASH --force-publish=* --no-changelog --no-push --no-git-tag-version --yes
      env:
        CI: true
      - name: Build
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: |
          yarn build
        env:
          CI: true
      - name: Set .npmrc file
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm whoami
      - name: Publish nightly to NPM
        if: ${{ steps.check-npm-token.outputs.is-ok }}
        run: yarn publish
        env:
          CI: true
